project:
  name: "Parcial 1 - Big Data"

data:
  input_path: "data/raw/sdss_sample_pro.csv"
  processed_path: "data/processed/processed_data.csv"
  features_path: "data/features/features_data.csv"

split:
  test_size: 0.3
  random_state: 42

classification:
  features: [
    "u", "g", "r", "i", "z", "redshift",
    "u_g", "g_r", "r_i", "i_z"
  ]
  target: "class"

regression:
  features: [
    "u", "g", "r", "i", "z",
    "u_g", "g_r", "r_i", "i_z"
  ]
  target: "redshift"

clustering:
  features: [
    "u", "g", "r", "i", "z", 
    "u_g", "g_r", "r_i", "i_z"
  ]
  n_clusters: 3